package server.enums.error;

public enum ErrorType {
    SUCCESS,
    REQUIRED_FIELD_EMPTY,

    DOESNT_EXIST,
    DUPLICATED_USERNAME,
    ALREADY_VOTED,
    INVALID_PASS,
    MISMATCH,
    DUPLICATED_EMAIL,
    INVALID_EMAIL,
    DUPLICATED_PHONE_NUMBER,
    INVALID_PHONE_NUMBER,
    INVALID_BIRTHDATE,
    UNDER_AGE,
    TOO_LONG,
    BLOCKED,
    ALREADY_EXIST,
    ALREADY_LIKED,
    HAVE_NOT_LIKED,
    PERMISSION_DENIED,
    HAVE_NOT_FOLLOWED,
    HAVE_NOT_BLOCKED,
    NOT_VALID_COUNTRY
}
